keys:
  users:
    me: &me age1rdwj0vjjre2lm8esr5jpvn3yetwc02tahc0uyc5yxlvxpsrkgcwsdpf0ae
  hosts:
    fluffy: &fluffy age1gkxux2ufu0aww573rnl453cke42jegtugxtq0325lxnj43xkgsrsfq2x89
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *me
          - *fluffy
