keys:
  users:
    me: &me age1rdwj0vjjre2lm8esr5jpvn3yetwc02tahc0uyc5yxlvxpsrkgcwsdpf0ae
  hosts:
    cloudy: &cloudy age1zwjx2wdxrqtj95rxrymnrp60fhwntjytm5eehgq7p382xswx8c3qenzs7d
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *me
          - *cloudy
