keys:
  users:
    me: &me age185pa0v8737f3k4rrkzq0qntpqc0wsmkvl23u7sl59y2a2t6y6sdqamhr3j
  hosts:
    fluffy: &fluffy age1gkxux2ufu0aww573rnl453cke42jegtugxtq0325lxnj43xkgsrsfq2x89
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *me
          - *fluffy
