keys:
  users:
    me: &me age1rdwj0vjjre2lm8esr5jpvn3yetwc02tahc0uyc5yxlvxpsrkgcwsdpf0ae
  hosts:
    fluffy: &fluffy age16ellsz2z4ytsstm0mdxuuj5uj9zrn9metgpe50xw43tfq59dya9szzl558
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *me
          - *fluffy
