keys:
  users:
    me: &me "age185pa0v8737f3k4rrkzq0qntpqc0wsmkvl23u7sl59y2a2t6y6sdqamhr3j"
  hosts:
    fluffy: &fluffy "age15ss6xsumnwzfk248yzgtw4whd27k6ft8efwagdyp9pnk56y879lqj8hdxz"
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *me
          - *fluffy
